name: Code Review Bot

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the diff of the current commit
        run: |
          git fetch origin master --depth=2 || true
          git diff HEAD^ HEAD > diff.py

      - name: Call Review API
        id: call_review_api
        run: |
          REVIEW_COMMENT=$(curl --silent --location 'https://tidy-beers-crash.loca.lt/review' \
            --form 'file=@"diff.py"' \
            --form 'language="python"')
          echo "REVIEW_COMMENT<<EOF" >> $GITHUB_ENV
          echo "$REVIEW_COMMENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEW_COMMENT: ${{ env.REVIEW_COMMENT }}
        run: |
          if [[ -n "$REVIEW_COMMENT" ]]; then
            ESCAPED_COMMENT=$(echo "$REVIEW_COMMENT" | jq -Rs .)
            curl -X POST \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"body\": $ESCAPED_COMMENT}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments"
          else
            echo "No review comment to post."
          fi
