name: Code Review Workflow

on:
  push:
    branches:
      - main  # or any branch you want to track commits for

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid issues with git diff

      # Step 2: Get the diff of the staged changes
      - name: Get the diff of the current commit
        id: diff
        run: |
          git diff --cached > diff.txt
          echo "::set-output name=diff::$(cat diff.txt)"

      # Step 3: Call the external review API and get the review comment
      - name: Call external review API and get review comment
        id: review_api
        run: |
          review_comment=$(curl --location 'http://your-api-url' --form 'file=@diff.txt' --form 'language="python"')
          echo "::set-output name=review_comment::${review_comment}"

      # Step 4: Add comment to the commit
      - name: Add comment to commit
        run: |
          if [[ -n "${{ steps.review_api.outputs.review_comment }}" ]]; then
            curl -X POST \
              -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -d "{\"body\": \"${{ steps.review_api.outputs.review_comment }}\"}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments"
          else
            echo "No review comment to post."
          fi
