name: Code Review Bot

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the diff of the current commit
        run: |
          git fetch origin main --depth=2 || true
          git diff HEAD^ HEAD > diff.py

      - name: Call Review API
        id: call_review_api
        run: |
          REVIEW_COMMENT=$(curl --silent --location 'https://tidy-beers-crash.loca.lt/review' \
            --form 'file=@"diff.py"' \
            --form 'language="python"')
          echo "Review Comment:"
          echo "$REVIEW_COMMENT"

      - name: Show Review in Logs
        run: |
          echo "Review of the commit: $REVIEW_COMMENT"
