name: Code Review CI

# Trigger the workflow on every commit to any branch
on:
  push:
    branches:
      - '*'  # Trigger on all branches. You can specify specific branches if needed.

jobs:
  review:
    runs-on: ubuntu-latest  # You can use another OS if needed (ubuntu-latest is used here)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out the code in your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use a specific Python version if needed

      - name: Install curl and git
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git jq  # Install curl, git, and jq (for parsing JSON)

      - name: Get git diff and send to review API
        run: |
          # Get the diff of the current commit
          git diff HEAD^ > diff_output.diff  # Adjust as necessary to capture the diff

          # Send the git diff to your review API without authentication and capture the response
          response=$(curl --silent --location 'https://wild-buses-ring.loca.lt/review' \
            --form 'file=@diff_output.diff' \
            --form 'language="diff"')

          # Extract review comment from the response (assuming the review is inside the 'review' key)
          review_comment=$(echo $response | jq -r '.review')

          # Check if jq and response parsing worked
          if [ "$review_comment" != "null" ]; then
            echo "Review Comment: $review_comment"
          else
            echo "No review comment found in the response."
          fi

      - name: Comment on commit with review output
        run: |
          # Add comment on the commit using GitHub API
          if [[ -n "$review_comment" ]]; then
            curl -X POST \
              -d "{\"body\": \"$review_comment\"}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments"
          else
            echo "No review comment to post."
          fi
